### ISSUE TITLE
poll thing

### ISSUE THREAD

**Issue by LankyBox01** [GrahamSH-LLK/contact#2]
How did you do the poll thing on the scratch forums
Idk how to send the poll data in a post request

Honestly i don't even know how to send any kind of data in a post request.

**Comment by GrahamSH-LLK** [comment]
Take a look at https://scratch.mit.edu/projects/512523539/!

**Comment by GrahamSH-LLK** [comment]
@CodeGuy92

**Comment by LankyBox01** [comment]
Yay

**Comment by LankyBox01** [comment]
and it was banned... oof

Can u unshare the project so u dont receive an alert
